daftar_mahasiswa = [
    {
        'nama_lengkap': 'Akbar',
        'nim': '131202101',
        'id': 1,
        'jurusan': 'Sistem Informasi',
        'tgl_lahir': '01 Maret 2003',
        'nilai': '3.2',
        'semester': 3,
        'is_active': False,
    },
    {
        'nama_lengkap': 'adit',
        'nim': '131202102',
        'id': 2,
        'jurusan': 'hukum',
        'tgl_lahir': '01 Maret 1945',
        'nilai': '3.9',
        'semester': 20,
        'is_active': True,
    },
    {
        'nama_lengkap': 'qwery',
        'nim': '131202103',
        'id': 3,
        'jurusan': 'Teknik Informasi',
        'tgl_lahir': '01 Maret 1978',
        'nilai': '3.4',
        'semester': 8,
        'is_active': False,
    },
    {
        'nama_lengkap': 'chokiz',
        'nim': '131202104',
        'id': 4,
        'jurusan': 'Sistem Informasi',
        'tgl_lahir': '01 Maret 2000',
        'nilai': '3.6',
        'semester': 5,
        'is_active': False,
    },
    {
        'nama_lengkap': 'poco',
        'nim': '131202105',
        'id': 5,
        'jurusan': 'Teknik Industri',
        'tgl_lahir': '01 Maret 1999',
        'nilai': '3.0',
        'semester': 7,
        'is_active': True,
    },
]